// Regenerate src/styles.ts from Tailwind. Run after changing any classes:
//   npm run build:css
// Keeps deploy build-free: the compiled CSS is committed and inlined by src/html.ts.
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

execSync('node_modules/.bin/tailwindcss -i src/input.css -o /tmp/_splitter_app.css --minify', { stdio: 'inherit' });
const css = readFileSync('/tmp/_splitter_app.css', 'utf8').trim();
writeFileSync('src/styles.ts', '// AUTO-GENERATED by scripts/build-css.mjs — do not edit by hand. Run: npm run build:css\nexport const TAILWIND_CSS = ' + JSON.stringify(css) + ';\n');
console.log('Wrote src/styles.ts (' + css.length + ' bytes of CSS)');
